# -*- coding: utf-8 -*-
"""tempo_detection

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q5h3ivGc6yywrNYNT2zepLydqCy0fbSG
"""

import essentia
import essentia.standard as es
import math

import os

features, features_frames = es.MusicExtractor(lowlevelStats=['mean', 'stdev'],
                                              rhythmStats=['mean', 'stdev'],
                                              tonalStats=['mean', 'stdev'])('1 19.wav')

print("BPM: ", features['rhythm.bpm'])

bpm = features['rhythm.bpm']

bpm = round(bpm)

print("BPM: ", bpm)

f = open("tempos.txt", "a")
f.write("{}".format(bpm))
f.close()